


server:
  port: 8085

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://127.0.0.1/rbac?seUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,resources/**,static/**,templates/**


mybatis:
  type-aliases-package: com.shiguiwu.admin.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:  classpath:mapper/*.xml
  # cache-enabled: true

api-url: /api


logging:
  level:
    com.shiguiwu.admin.mapper: debug
